// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type UserCard struct {
	ID             int64  `json:"id"`
	UserID         int64  `json:"user_id"`
	NoteID         int64  `json:"note_id"`
	DeckID         int64  `json:"deck_id"`
	Ordinal        int64  `json:"ordinal"`
	ModifiedAt     int64  `json:"modified_at"`
	Usn            int64  `json:"usn"`
	State          int64  `json:"state"`
	Queue          int64  `json:"queue"`
	Due            int64  `json:"due"`
	Interval       int64  `json:"interval"`
	EaseFactor     int64  `json:"ease_factor"`
	Reps           int64  `json:"reps"`
	Lapses         int64  `json:"lapses"`
	LeftCount      int64  `json:"left_count"`
	OriginalDue    int64  `json:"original_due"`
	OriginalDeckID int64  `json:"original_deck_id"`
	Flags          int64   `json:"flags"`
	Data           string  `json:"data"`
	Stability      float64 `json:"stability"`
	Difficulty     float64 `json:"difficulty"`
}

type UserCollection struct {
	UserID   int64        `json:"user_id"`
	Usn      int64        `json:"usn"`
	LastSync sql.NullTime `json:"last_sync"`
}

type UserDeck struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ConfigID    sql.NullInt64  `json:"config_id"`
	CreatedAt   int64          `json:"created_at"`
	ModifiedAt  int64          `json:"modified_at"`
	Usn         int64          `json:"usn"`
}

type UserGrafe struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	Usn    int64 `json:"usn"`
	Oid    int64 `json:"oid"`
	Type   int64 `json:"type"`
}

type UserMedium struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	Filename string `json:"filename"`
	Hash     string `json:"hash"`
	Size     int64  `json:"size"`
	Usn      int64  `json:"usn"`
}

type UserNote struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Guid   string `json:"guid"`
	Mid    int64  `json:"mid"`
	Mod    int64  `json:"mod"`
	Usn    int64  `json:"usn"`
	Tags   string `json:"tags"`
	Flds   string `json:"flds"`
	Sfld   string `json:"sfld"`
	Csum   int64  `json:"csum"`
	Flags  int64  `json:"flags"`
	Data   string `json:"data"`
}
