// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateSyncMeta(ctx context.Context, userID int64) error
	DeleteSpecificCard(ctx context.Context, arg DeleteSpecificCardParams) error
	DeleteSpecificDeck(ctx context.Context, arg DeleteSpecificDeckParams) error
	DeleteSpecificNote(ctx context.Context, arg DeleteSpecificNoteParams) error
	DeleteUserCards(ctx context.Context, userID int64) error
	DeleteUserDecks(ctx context.Context, userID int64) error
	DeleteUserGraves(ctx context.Context, userID int64) error
	DeleteUserMedia(ctx context.Context, userID int64) error
	DeleteUserNotes(ctx context.Context, userID int64) error
	GetCardsSince(ctx context.Context, arg GetCardsSinceParams) ([]GetCardsSinceRow, error)
	GetDecksSince(ctx context.Context, arg GetDecksSinceParams) ([]GetDecksSinceRow, error)
	GetGravesSince(ctx context.Context, arg GetGravesSinceParams) ([]GetGravesSinceRow, error)
	GetNotesSince(ctx context.Context, arg GetNotesSinceParams) ([]GetNotesSinceRow, error)
	GetSyncMeta(ctx context.Context, userID int64) (GetSyncMetaRow, error)
	GetUSN(ctx context.Context, userID int64) (int64, error)
	RecordGrave(ctx context.Context, arg RecordGraveParams) error
	ResetUserUSN(ctx context.Context, userID int64) error
	UpdateUSN(ctx context.Context, userID int64) (int64, error)
	UpsertCard(ctx context.Context, arg UpsertCardParams) error
	UpsertDeck(ctx context.Context, arg UpsertDeckParams) error
	UpsertNote(ctx context.Context, arg UpsertNoteParams) error
}

var _ Querier = (*Queries)(nil)
