// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// MediaItem defines model for MediaItem.
type MediaItem struct {
	Filename *string `json:"filename,omitempty"`
	Hash     *string `json:"hash,omitempty"`
}

// MediaListResponse defines model for MediaListResponse.
type MediaListResponse struct {
	Media *[]MediaItem `json:"media,omitempty"`
}

// MediaUploadResponse defines model for MediaUploadResponse.
type MediaUploadResponse struct {
	Hash   *string `json:"hash,omitempty"`
	Status *string `json:"status,omitempty"`
}

// SyncCard defines model for SyncCard.
type SyncCard struct {
	Data           string `json:"data"`
	DeckId         int64  `json:"deck_id"`
	Due            int64  `json:"due"`
	EaseFactor     int    `json:"ease_factor"`
	Flags          int    `json:"flags"`
	Id             int64  `json:"id"`
	Interval       int    `json:"interval"`
	Lapses         int    `json:"lapses"`
	LeftCount      int    `json:"left_count"`
	ModifiedAt     int64  `json:"modified_at"`
	NoteId         int64  `json:"note_id"`
	Ordinal        int    `json:"ordinal"`
	OriginalDeckId int64  `json:"original_deck_id"`
	OriginalDue    int64  `json:"original_due"`
	Queue          int    `json:"queue"`
	Reps           int    `json:"reps"`
	State          int     `json:"state"`
	Usn            int     `json:"usn"`
	Stability      float64 `json:"stability"`
	Difficulty     float64 `json:"difficulty"`
}

// SyncDeck defines model for SyncDeck.
type SyncDeck struct {
	ConfigId    int     `json:"config_id"`
	CreatedAt   int64   `json:"created_at"`
	Description *string `json:"description,omitempty"`
	Id          int64   `json:"id"`
	ModifiedAt  int64   `json:"modified_at"`
	Name        string  `json:"name"`
	Usn         int     `json:"usn"`
}

// SyncGrave defines model for SyncGrave.
type SyncGrave struct {
	Oid int64 `json:"oid"`

	// Type 0=card, 1=note, 2=deck
	Type int `json:"type"`
}

// SyncMeta defines model for SyncMeta.
type SyncMeta struct {
	LastSync *time.Time `json:"last_sync,omitempty"`
	UserId   *int       `json:"user_id,omitempty"`
	Usn      *int       `json:"usn,omitempty"`
}

// SyncNote defines model for SyncNote.
type SyncNote struct {
	Csum  int64  `json:"csum"`
	Data  string `json:"data"`
	Flags int    `json:"flags"`
	Flds  string `json:"flds"`
	Guid  string `json:"guid"`
	Id    int64  `json:"id"`
	Mid   int64  `json:"mid"`
	Mod   int64  `json:"mod"`
	Sfld  string `json:"sfld"`
	Tags  string `json:"tags"`
	Usn   int    `json:"usn"`
}

// SyncPullResponse defines model for SyncPullResponse.
type SyncPullResponse struct {
	Cards     *[]SyncCard  `json:"cards,omitempty"`
	Decks     *[]SyncDeck  `json:"decks,omitempty"`
	Graves    *[]SyncGrave `json:"graves,omitempty"`
	Notes     *[]SyncNote  `json:"notes,omitempty"`
	ServerUsn *int         `json:"server_usn,omitempty"`
}

// SyncPushRequest defines model for SyncPushRequest.
type SyncPushRequest struct {
	Cards     *[]SyncCard  `json:"cards,omitempty"`
	ClientUsn *int         `json:"client_usn,omitempty"`
	Decks     *[]SyncDeck  `json:"decks,omitempty"`
	Graves    *[]SyncGrave `json:"graves,omitempty"`
	Notes     *[]SyncNote  `json:"notes,omitempty"`
}

// USNResponse defines model for USNResponse.
type USNResponse struct {
	ServerUsn *int `json:"server_usn,omitempty"`
}

// UploadMediaMultipartBody defines parameters for UploadMedia.
type UploadMediaMultipartBody struct {
	File openapi_types.File `json:"file"`
	Hash string             `json:"hash"`
}

// PullSyncParams defines parameters for PullSync.
type PullSyncParams struct {
	// Since Last known USN
	Since *int `form:"since,omitempty" json:"since,omitempty"`
}

// FullSyncJSONRequestBody defines body for FullSync for application/json ContentType.
type FullSyncJSONRequestBody = SyncPushRequest

// UploadMediaMultipartRequestBody defines body for UploadMedia for multipart/form-data ContentType.
type UploadMediaMultipartRequestBody UploadMediaMultipartBody

// PushSyncJSONRequestBody defines body for PushSync for application/json ContentType.
type PushSyncJSONRequestBody = SyncPushRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Full sync (reset and push)
	// (POST /sync/full)
	FullSync(w http.ResponseWriter, r *http.Request)
	// List user media files
	// (GET /sync/media/list)
	ListMedia(w http.ResponseWriter, r *http.Request)
	// Upload media file
	// (POST /sync/media/upload)
	UploadMedia(w http.ResponseWriter, r *http.Request)
	// Download media file
	// (GET /sync/media/{hash})
	DownloadMedia(w http.ResponseWriter, r *http.Request, hash string)
	// Get sync metadata
	// (GET /sync/meta)
	GetSyncMeta(w http.ResponseWriter, r *http.Request)
	// Pull changes from server
	// (GET /sync/pull)
	PullSync(w http.ResponseWriter, r *http.Request, params PullSyncParams)
	// Push changes to server
	// (POST /sync/push)
	PushSync(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Full sync (reset and push)
// (POST /sync/full)
func (_ Unimplemented) FullSync(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List user media files
// (GET /sync/media/list)
func (_ Unimplemented) ListMedia(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload media file
// (POST /sync/media/upload)
func (_ Unimplemented) UploadMedia(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download media file
// (GET /sync/media/{hash})
func (_ Unimplemented) DownloadMedia(w http.ResponseWriter, r *http.Request, hash string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get sync metadata
// (GET /sync/meta)
func (_ Unimplemented) GetSyncMeta(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Pull changes from server
// (GET /sync/pull)
func (_ Unimplemented) PullSync(w http.ResponseWriter, r *http.Request, params PullSyncParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Push changes to server
// (POST /sync/push)
func (_ Unimplemented) PushSync(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// FullSync operation middleware
func (siw *ServerInterfaceWrapper) FullSync(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FullSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMedia operation middleware
func (siw *ServerInterfaceWrapper) ListMedia(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMedia(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadMedia operation middleware
func (siw *ServerInterfaceWrapper) UploadMedia(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadMedia(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadMedia operation middleware
func (siw *ServerInterfaceWrapper) DownloadMedia(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadMedia(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSyncMeta operation middleware
func (siw *ServerInterfaceWrapper) GetSyncMeta(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSyncMeta(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PullSync operation middleware
func (siw *ServerInterfaceWrapper) PullSync(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PullSyncParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PullSync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PushSync operation middleware
func (siw *ServerInterfaceWrapper) PushSync(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PushSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sync/full", wrapper.FullSync)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sync/media/list", wrapper.ListMedia)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sync/media/upload", wrapper.UploadMedia)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sync/media/{hash}", wrapper.DownloadMedia)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sync/meta", wrapper.GetSyncMeta)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sync/pull", wrapper.PullSync)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sync/push", wrapper.PushSync)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYUW/bNhD+KwS3hw1Qa6fN9iAgD+mKBhmWLKgX7CEIDEY6WWwoUiGPKbzA/30gaVuS",
	"RWVSsPRh2Jstnu6O3/fd8agnmqmqVhIkGpo+UZOVUDH/8wJyzs4RKven1qoGjRz8UsEFSFaB+43rGmhK",
	"DWouV3ST0JKZMrKwSXZP1N0XyNCZ+hC/cYOfwdRKGuiHqpyJ+8ERKv/kew0FTel3sybz2TbtWZNzE45p",
	"zdbPxL+uhWL5cAYD+0moQYbWjNzqYi2zX5jO+/5zhizqP4fsfsn9G4XSFUOaUi7x52O6988lwgq0t7Yw",
	"0hKYgWXBMlS6FbdlUAi2MvGl0em4n/qRibgbwWoDAyEEFLjMlJUYX69UzgsO+ZLhyFykQhgPpNI5l0OJ",
	"K81XbnU5jZzmtdEsPViwEE9CQz2AnZPkwEvWyNiCd/dguYacpjeO3wavRoINKl38g9td3F3SQYwtDXQ1",
	"t93AXgUdyg+wiiC+02cSKud2oNg+QnbfL7ZMyYKvtsT1Qco0MJwirRxMpnmNXMloDY9WyAtUPdSApzDt",
	"fCQtVDoQxLgegvtMs8dI81SjAQhPnrqI0vlJxnSekKMTJ8qEvDtxMog4ONid8nvxRkMZX0Dou92EBTO4",
	"NGuZddLOGcIb5B6sCN6gBxU1TEY0qUuFERQzY6uxghw6TZ5p6oXITfSdle1s6yWynlIAIy1NIeJZYXeH",
	"L6oIv+WQd8hp1+Iw9ByP1TaHJBAzsiFdWSGGpwwnczN6ztlPE70xJ/TsaZ58q4x4WrmanuYqtIGIL1e+",
	"01z5Uoh4MqAfQS8nFtaVNeVneLBg8DXBzwQHiUPJ/dfJiYF/vbgcVv1ULj39mdUc1wuXTfByB0yDPrVY",
	"Nv8+7frIr3/+4erVW9N0u9r0lRKxppuNn1gL1T+ATq/OSaE0cUdCqZXkf3G5IqfynpNCMFM66RBf9wlF",
	"jsL5/L0G6S0cUuT06pwm9BG0CR6P3s7fzv1QWINkNacpfe8fJbRmWPodzVy4WWGFH0NrFUTrkGMur/Oc",
	"pvSTFcIFoKGLgcEPKl9vhxyEMD6zuhY88y/NvpgwpAQex7DcLppNt12ituAfBGp91u/m838tfFs2PnSX",
	"loXNMjCmsMIz4+A8nr/v07ewd/u/ZJ/9JqE/hVwPrL0cCWitgvyMrSqm11u0fSjygwYDSJjMSW1N+aM3",
	"DIT5y+pM8EDXCiKsuduuv3bSVwSvf6+OQOjWiSqIT5q4K715CTDejRuBuo4OMLH+kj0s5nAJb4AZ0nNl",
	"BfKaaZy5QeHNbtppYOl/qOhMFXdcurSTKZ8t2jOCd7g17h/037ZEYl8vIjwHC2L2FROKJcLyB5YTvSv3",
	"6UrYBmpk0FPBk8NtM1gbH9VX2ZZBzTSrAEEbmt48Ue7iuxa5u7ikgYdDzJMWfods3k7iQ2UI+MagBlZ1",
	"eflHQfV5uGjh4gg47oN7ATkjUiEplJX5Abw7dIYADpUQBfYMcH/jeUVB7mM837D1XqzTNXYGGLqw26+v",
	"/gaCentcRiG4ak7LA1kddEVmkNxL9VWS68Wl/4hBU/pgwZO8lZ3hMgMa0Vkzuty+Ms6d28TzeHtcXv2A",
	"dAmRrGRyBYYUWlUkDHcdgkKLjR8Bbtj4f54Rfqj4FnSZck8Xqoas1ojty6M9XN/cOl0H01A8Vgua0hmr",
	"+ezxiG5uN38HAAD///x6dDZRGAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
